# Generated by Django 5.0.7 on 2025-01-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
        ('transactions', '0010_alter_transaction_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='case',
        ),
        migrations.AddField(
            model_name='penalty',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.invoice'),
            preserve_default=False,
        ),
    ]
