# Generated by Django 5.0.7 on 2025-02-01 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0003_penalty_comment'),
        ('transactions', '0015_alter_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.invoice'),
        ),
    ]
