"""
Django settings for contribution_management project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv.main import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k@udu=bk+2vmiwgn52r48e46cd0wh_0-e$)q!k8q6p%h2keqv2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    'members',
    'cases',
    'transactions',
    'penalties',
    'notifications',
    'mpesa',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

LOGIN_REDIRECT_URL = 'dashboard_view'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

ROOT_URLCONF = 'contribution_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contribution_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Africa's Talking API credentials
# settings.py
AFRICA_TALKING_USERNAME = os.getenv('AFRICA_TALKING_USERNAME')
AFRICA_TALKING_API_KEY = os.getenv('AFRICA_TALKING_API_KEY')
AFRICA_TALKING_API_URL = os.getenv('AFRICA_TALKING_API_URL')
AFRICA_TALKING_AUTH_TOKEN_URL = os.getenv('AFRICA_TALKING_AUTH_TOKEN_URL')

# Mpesa settings
MPESA_ENV = os.getenv('MPESA_ENV')
MPESA_CONSUMER_KEY = os.getenv('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = os.getenv('MPESA_CONSUMER_SECRET')
MPESA_SHORTCODE = os.getenv('MPESA_SHORTCODE')
CONFIRMATION_URL = os.getenv('MPESA_CONFIRMATION_URL')
VALIDATION_URL = os.getenv('VALIDATION_URL')

# Penalty settings
PENALTY_AMOUNT = os.getenv('PENALTY_AMOUNT')

if MPESA_ENV == 'sandbox':
    # Mpesa sandbox URLs
    MPESA_BASE_URL = "https://sandbox.safaricom.co.ke/"
    MPESA_AUTH_URL = (
        MPESA_BASE_URL + "oauth/v1/generate?grant_type=client_credentials"
    )
    MPESA_REGISTER_URL = MPESA_BASE_URL + "mpesa/c2b/v1/registerurl"
else:
    # Mpesa live URLs
    MPESA_BASE_URL = "https://api.safaricom.co.ke/"
    MPESA_AUTH_URL = (
        MPESA_BASE_URL + "oauth/v1/generate?grant_type=client_credentials"
    )
    MPESA_REGISTER_URL = MPESA_BASE_URL + "mpesa/c2b/v1/registerurl"
