# Generated by Django 5.0.7 on 2024-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_invoice_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
