# Generated by Django 5.0.7 on 2024-07-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('transactions', '0003_alter_transaction_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
