# Generated by Django 5.0.7 on 2024-07-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('transactions', '0004_invoice_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='case',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
            preserve_default=False,
        ),
    ]
