# Generated by Django 5.0.7 on 2025-01-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_invoice_case'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnmatchedTransactions',
            new_name='UnmatchedTransaction',
        ),
    ]
