# Generated by Django 5.0.7 on 2025-01-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_unmatchedtransactions_unmatchedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
