# Generated by Django 5.0.7 on 2025-01-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmatchedtransaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unmatchedtransaction',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
