# Generated by Django 5.0.7 on 2025-01-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_unmatchedtransaction_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(choices=[('INVOICE_PAYMENT', 'Invoice Payment'), ('PENALTY_PAYMENT', 'Penalty Payment'), ('ACCOUNT_TOPUP', 'Account Top-up'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
