# Generated by Django 5.0.7 on 2025-01-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('transactions', '0010_alter_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(choices=[('INVOICE_CREATION', 'Invoice Creation'), ('INVOICE_PAYMENT', 'Invoice Payment'), ('PENALTY_PAYMENT', 'Penalty Payment'), ('ACCOUNT_TOPUP', 'Account Top-up'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
