# Generated by Django 5.0.7 on 2025-01-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_invoice_case_alter_transaction_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(choices=[('INVOICE_CREATION', 'Invoice Creation'), ('INVOICE_PAYMENT', 'Invoice Payment'), ('INV_PARTIAL_PAY', 'Inv Partial Pay'), ('PENALTY_PAYMENT', 'Penalty Payment'), ('ACCOUNT_TOPUP', 'Account Top-up'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
