# Generated by Django 5.0.7 on 2025-01-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_invoice_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='outstanding_balance',
        ),
    ]
