# Generated by Django 5.0.7 on 2025-01-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_invoice_outstanding_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
