# Generated by Django 5.0.7 on 2025-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_invoice_outstanding_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(choices=[('INVOICE_CREATION', 'Invoice Creation'), ('INVOICE_PAYMENT', 'Invoice Payment'), ('INV_PARTIAL_PAY', 'Inv Partial Pay'), ('PENALTY_PAYMENT', 'Penalty Payment'), ('ACCOUNT_TOPUP', 'Account Top-up')], default='ACCOUNT_TOPUP', max_length=20),
        ),
    ]
