# Generated by Django 5.0.7 on 2025-02-01 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: +254712345678' and contain only digits after the '+'.", regex='^\\+\\d{10,15}$')]),
        ),
    ]
