# Generated by Django 5.0.7 on 2025-01-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_sentmessage_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='status',
        ),
    ]
